process.env.NODE_ENV = 'test'
process.env.DATABASE_URL = process.env.DATABASE_URL || 'postgresql://postgres:postgres@localhost:5432/alvenqis_network_test?schema=public'
process.env.JWT_SECRET = process.env.JWT_SECRET || 'test-access-secret-at-least-16'
process.env.JWT_REFRESH_SECRET = process.env.JWT_REFRESH_SECRET || 'test-refresh-secret-at-least-16'
process.env.CORS_ORIGIN = process.env.CORS_ORIGIN || 'http://localhost:5173'
process.env.RATE_LIMIT_MAX = process.env.RATE_LIMIT_MAX || '1000'
